export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const STORE_CATEGORY = 'STORE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';