export const categoryTypes = {
    GET_CATEGORY_BY_ID: 'GET_CATEGORY_BY_ID',
    STORE_SELECTED_CATEGORY: 'STORE_SELECTED_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    CLEAR_SELECTED_CATEGORY: 'CLEAR_SELECTED_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    STORE_ALL_CATEGORIES: 'STORE_ALL_CATEGORIES',
}