export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const STORE_SELECTED_CATEGORY = 'STORE_SELECTED_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CLEAR_SELECTED_CATEGORY = 'CLEAR_SELECTED_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const STORE_ALL_CATEGORIES = 'STORE_ALL_CATEGORIES';