export const GET_ENTRY_BY_ID = 'GET_ENTRY_BY_ID';
export const STORE_SELECTED_ENTRY = 'STORE_SELECTED_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const CREATE_ENTRY = 'CREATE_ENTRY';
export const CLEAR_SELECTED_ENTRY = 'CLEAR_SELECTED_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const STORE_ALL_ENTRIES = 'STORE_ALL_ENTRIES';
