export const GET_FINANCIAL_TRANSACTION_BY_ID = 'GET_FINANCIAL_TRANSACTION_BY_ID';
export const STORE_SELECTED_FINANCIAL_TRANSACTION = 'STORE_SELECTED_FINANCIAL_TRANSACTION';
export const UPDATE_FINANCIAL_TRANSACTION = 'UPDATE_FINANCIAL_TRANSACTION';
export const CREATE_FINANCIAL_TRANSACTION = 'CREATE_FINANCIAL_TRANSACTION';
export const CLEAR_SELECTED_FINANCIAL_TRANSACTION = 'CLEAR_SELECTED_FINANCIAL_TRANSACTION';
export const DELETE_FINANCIAL_TRANSACTION = 'DELETE_FINANCIAL_TRANSACTION';
export const FETCH_FINANCIAL_TRANSACTIONS = 'FETCH_FINANCIAL_TRANSACTIONS';
export const STORE_ALL_FINANCIAL_TRANSACTIONS = 'STORE_ALL_FINANCIAL_TRANSACTIONS';
