export const GET_USER_DATA = 'GET_USER_DATA';
export const STORE_CURRENT_USER_DATA = 'STORE_CURRENT_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
