export const GET_VARIABLE_REVENUE_BY_ID = 'GET_VARIABLE_REVENUE_BY_ID';
export const STORE_SELECTED_VARIABLE_REVENUE = 'STORE_SELECTED_VARIABLE_REVENUE';
export const UPDATE_VARIABLE_REVENUE = 'UPDATE_VARIABLE_REVENUE';
export const CREATE_VARIABLE_REVENUE = 'CREATE_VARIABLE_REVENUE';
export const CLEAR_SELECTED_VARIABLE_REVENUE = 'CLEAR_SELECTED_VARIABLE_REVENUE';
export const DELETE_VARIABLE_REVENUE = 'DELETE_VARIABLE_REVENUE';
export const FETCH_VARIABLES_REVENUES = 'FETCH_VARIABLES_REVENUES';
export const STORE_ALL_VARIABLES_REVENUES = 'STORE_ALL_VARIABLES_REVENUES';
