export const GET_VARIABLE_EXPENSE_BY_ID = 'GET_VARIABLE_EXPENSE_BY_ID';
export const STORE_SELECTED_VARIABLE_EXPENSE = 'STORE_SELECTED_VARIABLE_EXPENSE';
export const UPDATE_VARIABLE_EXPENSE = 'UPDATE_VARIABLE_EXPENSE';
export const CREATE_VARIABLE_EXPENSE = 'CREATE_VARIABLE_EXPENSE';
export const CLEAR_SELECTED_VARIABLE_EXPENSE = 'CLEAR_SELECTED_VARIABLE_EXPENSE';
export const DELETE_VARIABLE_EXPENSE = 'DELETE_VARIABLE_EXPENSE';
export const FETCH_VARIABLES_EXPENSES = 'FETCH_VARIABLES_EXPENSES';
export const STORE_ALL_VARIABLES_EXPENSES = 'STORE_ALL_VARIABLES_EXPENSES';
